//// GENERATED by scripts/gen-d3-fixtures.mjs — do not edit by hand.
////
//// Ground truth from d3-array 3.2.4 and d3-scale 4.0.2. dapper's tick and
//// scale implementations are ports, and a port is only a port if it is checked
//// against the original. These fixtures are what make that check possible
//// without requiring Node to run the suite.
////
//// Regenerate with: cd scripts && npm install && npm run gen

pub type TicksCase {
  TicksCase(start: Float, stop: Float, count: Int, ticks: List(Float))
}

pub type IncrementCase {
  IncrementCase(start: Float, stop: Float, count: Int, increment: Float)
}

pub type NiceCase {
  NiceCase(start: Float, stop: Float, count: Int, lo: Float, hi: Float)
}

pub type BandCase {
  BandCase(
    n: Int,
    lo: Float,
    hi: Float,
    padding_inner: Float,
    padding_outer: Float,
    align: Float,
    bandwidth: Float,
    step: Float,
    positions: List(Float),
  )
}

pub type PointCase {
  PointCase(
    n: Int,
    lo: Float,
    hi: Float,
    padding: Float,
    align: Float,
    step: Float,
    positions: List(Float),
  )
}

pub fn ticks_cases() -> List(TicksCase) {
  [
    TicksCase(0.0, 1.0, 10, [
      0.0,
      0.1,
      0.2,
      0.3,
      0.4,
      0.5,
      0.6,
      0.7,
      0.8,
      0.9,
      1.0,
    ]),
    TicksCase(0.0, 1.0, 5, [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]),
    TicksCase(0.0, 1.0, 3, [0.0, 0.5, 1.0]),
    TicksCase(0.0, 1.0, 2, [0.0, 0.5, 1.0]),
    TicksCase(0.0, 1.0, 1, [0.0, 1.0]),
    TicksCase(0.0, 10.0, 10, [
      0.0,
      1.0,
      2.0,
      3.0,
      4.0,
      5.0,
      6.0,
      7.0,
      8.0,
      9.0,
      10.0,
    ]),
    TicksCase(0.0, 100.0, 10, [
      0.0,
      10.0,
      20.0,
      30.0,
      40.0,
      50.0,
      60.0,
      70.0,
      80.0,
      90.0,
      100.0,
    ]),
    TicksCase(0.0, 1000.0, 5, [0.0, 200.0, 400.0, 600.0, 800.0, 1000.0]),
    TicksCase(1.0, 9.0, 5, [2.0, 4.0, 6.0, 8.0]),
    TicksCase(0.0, 0.5, 5, [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]),
    TicksCase(0.0, 0.1, 5, [0.0, 0.02, 0.04, 0.06, 0.08, 0.1]),
    TicksCase(0.0, 0.05, 5, [0.0, 0.01, 0.02, 0.03, 0.04, 0.05]),
    TicksCase(-1.0, 1.0, 10, [
      -1.0,
      -0.8,
      -0.6,
      -0.4,
      -0.2,
      0.0,
      0.2,
      0.4,
      0.6,
      0.8,
      1.0,
    ]),
    TicksCase(-5.0, 5.0, 5, [-4.0, -2.0, 0.0, 2.0, 4.0]),
    TicksCase(-100.0, -10.0, 5, [-100.0, -80.0, -60.0, -40.0, -20.0]),
    TicksCase(1.0, 1.0, 5, [1.0]),
    TicksCase(0.0, 0.0, 5, [0.0]),
    TicksCase(10.0, 0.0, 5, [10.0, 8.0, 6.0, 4.0, 2.0, 0.0]),
    TicksCase(1.0, -1.0, 5, [1.0, 0.5, 0.0, -0.5, -1.0]),
    TicksCase(0.001, 0.002, 5, [0.001, 0.0012, 0.0014, 0.0016, 0.0018, 0.002]),
    TicksCase(1_000_000.0, 2_000_000.0, 5, [
      1_000_000.0,
      1_200_000.0,
      1_400_000.0,
      1_600_000.0,
      1_800_000.0,
      2_000_000.0,
    ]),
    TicksCase(1.0e-7, 2.0e-7, 5, [
      1.0e-7,
      1.2e-7,
      1.4e-7,
      1.6e-7,
      1.8e-7,
      2.0e-7,
    ]),
    TicksCase(123.0, 456.0, 7, [150.0, 200.0, 250.0, 300.0, 350.0, 400.0, 450.0]),
    TicksCase(2.5, 7.5, 4, [3.0, 4.0, 5.0, 6.0, 7.0]),
    TicksCase(-0.3, 0.7, 5, [-0.2, 0.0, 0.2, 0.4, 0.6]),
  ]
}

pub fn increment_cases() -> List(IncrementCase) {
  [
    IncrementCase(0.0, 1.0, 10, -10.0),
    IncrementCase(0.0, 1.0, 5, -5.0),
    IncrementCase(0.0, 1.0, 3, -2.0),
    IncrementCase(0.0, 1.0, 2, -2.0),
    IncrementCase(0.0, 1.0, 1, 1.0),
    IncrementCase(0.0, 10.0, 10, 1.0),
    IncrementCase(0.0, 100.0, 10, 10.0),
    IncrementCase(0.0, 1000.0, 5, 200.0),
    IncrementCase(1.0, 9.0, 5, 2.0),
    IncrementCase(0.0, 0.5, 5, -10.0),
    IncrementCase(0.0, 0.1, 5, -50.0),
    IncrementCase(0.0, 0.05, 5, -100.0),
    IncrementCase(-1.0, 1.0, 10, -5.0),
    IncrementCase(-5.0, 5.0, 5, 2.0),
    IncrementCase(-100.0, -10.0, 5, 20.0),
    IncrementCase(0.001, 0.002, 5, -5000.0),
    IncrementCase(1_000_000.0, 2_000_000.0, 5, 200_000.0),
    IncrementCase(1.0e-7, 2.0e-7, 5, -50_000_000.0),
    IncrementCase(123.0, 456.0, 7, 50.0),
    IncrementCase(2.5, 7.5, 4, 1.0),
    IncrementCase(-0.3, 0.7, 5, -5.0),
  ]
}

pub fn nice_cases() -> List(NiceCase) {
  [
    NiceCase(0.0, 1.0, 10, 0.0, 1.0),
    NiceCase(0.0, 1.0, 5, 0.0, 1.0),
    NiceCase(0.0, 1.0, 3, 0.0, 1.0),
    NiceCase(0.0, 1.0, 2, 0.0, 1.0),
    NiceCase(0.0, 1.0, 1, 0.0, 1.0),
    NiceCase(0.0, 10.0, 10, 0.0, 10.0),
    NiceCase(0.0, 100.0, 10, 0.0, 100.0),
    NiceCase(0.0, 1000.0, 5, 0.0, 1000.0),
    NiceCase(1.0, 9.0, 5, 0.0, 10.0),
    NiceCase(0.0, 0.5, 5, 0.0, 0.5),
    NiceCase(0.0, 0.1, 5, 0.0, 0.1),
    NiceCase(0.0, 0.05, 5, 0.0, 0.05),
    NiceCase(-1.0, 1.0, 10, -1.0, 1.0),
    NiceCase(-5.0, 5.0, 5, -6.0, 6.0),
    NiceCase(-100.0, -10.0, 5, -100.0, 0.0),
    NiceCase(1.0, 1.0, 5, 1.0, 1.0),
    NiceCase(0.0, 0.0, 5, 0.0, 0.0),
    NiceCase(10.0, 0.0, 5, 10.0, 0.0),
    NiceCase(1.0, -1.0, 5, 1.0, -1.0),
    NiceCase(0.001, 0.002, 5, 0.001, 0.002),
    NiceCase(1_000_000.0, 2_000_000.0, 5, 1_000_000.0, 2_000_000.0),
    NiceCase(1.0e-7, 2.0e-7, 5, 1.0e-7, 2.0e-7),
    NiceCase(123.0, 456.0, 7, 100.0, 500.0),
    NiceCase(2.5, 7.5, 4, 2.0, 8.0),
    NiceCase(-0.3, 0.7, 5, -0.4, 0.8),
  ]
}

pub fn band_cases() -> List(BandCase) {
  [
    BandCase(3, 0.0, 300.0, 0.0, 0.0, 0.5, 100.0, 100.0, [0.0, 100.0, 200.0]),
    BandCase(
      3,
      0.0,
      300.0,
      0.1,
      0.1,
      0.5,
      87.09677419354838,
      96.77419354838709,
      [9.677419354838719, 106.45161290322581, 203.2258064516129],
    ),
    BandCase(
      4,
      0.0,
      100.0,
      0.2,
      0.0,
      0.5,
      21.05263157894737,
      26.315789473684212,
      [0.0, 26.315789473684212, 52.631578947368425, 78.94736842105263],
    ),
    BandCase(
      4,
      0.0,
      100.0,
      0.2,
      0.2,
      0.0,
      19.047619047619047,
      23.80952380952381,
      [0.0, 23.80952380952381, 47.61904761904762, 71.42857142857143],
    ),
    BandCase(
      4,
      0.0,
      100.0,
      0.2,
      0.2,
      1.0,
      19.047619047619047,
      23.80952380952381,
      [
        9.523809523809518,
        33.33333333333333,
        57.14285714285714,
        80.95238095238095,
      ],
    ),
    BandCase(1, 0.0, 50.0, 0.5, 0.25, 0.5, 25.0, 50.0, [12.5]),
    BandCase(
      5,
      20.0,
      220.0,
      0.05,
      0.5,
      0.5,
      31.932773109243698,
      33.61344537815126,
      [
        36.80672268907563,
        70.42016806722688,
        104.03361344537815,
        137.64705882352942,
        171.26050420168067,
      ],
    ),
    BandCase(2, 0.0, 100.0, 1.0, 0.0, 0.5, 0.0, 100.0, [0.0, 100.0]),
  ]
}

pub fn point_cases() -> List(PointCase) {
  [
    PointCase(3, 0.0, 300.0, 0.0, 0.5, 150.0, [0.0, 150.0, 300.0]),
    PointCase(4, 0.0, 90.0, 0.5, 0.5, 22.5, [11.25, 33.75, 56.25, 78.75]),
    PointCase(1, 0.0, 100.0, 0.0, 0.5, 100.0, [50.0]),
  ]
}
