//// Tick selection: a port of d3-array's 1–2–5 algorithm.
////
//// This is a **port**, not an interpretation. `test/d3_fixtures.gleam` holds
//// ground truth generated by running d3-array 3.2.4, and the suite asserts
//// against it case by case. Extended-Wilkinson scoring is explicitly cut from
//// v0.1 (decision S5): its density term makes tick selection depend on layout
//// and its legibility term needs text metrics, which is precisely the
//// ticks-to-layout fixpoint the two-pass layout bound exists to forbid.
////
//// Two substitutions were needed to make the port deterministic across
//// targets, and they pull in opposite directions:
////
//// - **`Math.log10` and `Math.pow` are replaced** by `format.exponent10` and
////   `format.power_of_ten`, which work by comparison against exact literals.
////   A one-ulp disagreement about `log10` flips a floor, which changes a step,
////   which changes every tick on the axis (decision S6).
////
//// - **`Math.round` is kept, exactly.** `format.round_toward_positive`
////   reproduces JavaScript's half-toward-positive-infinity rule rather than the
////   BEAM's half-away-from-zero. d3 is a JavaScript library and the fixtures
////   come from running it, so rounding "better" here would mean rounding
////   *differently from the thing being ported*, and `-1.5` would land on a
////   different tick boundary.
////
//// Where d3 returns `NaN` — degenerate and reversed ranges — this returns
//// `Error(Nil)`. Gleam cannot represent NaN, and `render` must be total, so the
//// impossible value becomes an explicit absence.

import dapper/format
import gleam/float
import gleam/int

/// `sqrt(50)`, `sqrt(10)`, `sqrt(2)`: the geometric midpoints between 1, 2, 5
/// and 10. A step is rounded to whichever of those it is closest to *in the
/// logarithmic sense*, which is why the thresholds are irrational rather than
/// the arithmetic midpoints 1.5, 3.5, 7.5.
const e10 = 7.071_067_811_865_476

const e5 = 3.162_277_660_168_379_5

const e2 = 1.414_213_562_373_095_1

/// The step between ticks, and the bounds of the tick sequence expressed as
/// integer multiples of it.
///
/// `increment` is negative when it represents a *reciprocal* — d3's trick for
/// sub-unit steps, where dividing by `1/inc` avoids the rounding error that
/// multiplying by a repeating fraction would introduce. `0.1` is not
/// representable in binary, `10.0` is.
type Spec {
  Spec(i1: Int, i2: Int, increment: Float)
}

/// The ticks between `start` and `stop`, approximately `count` of them.
///
/// Returns them in descending order when `stop < start`, matching d3, so that
/// an inverted axis produces labels in the direction the axis runs.
///
/// ```gleam
/// ticks(0.0, 1.0, 5)   // [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
/// ticks(0.0, 1.0, 10)  // [0.0, 0.1, ..., 1.0]
/// ticks(10.0, 0.0, 5)  // [10.0, 8.0, 6.0, 4.0, 2.0, 0.0]
/// ```
pub fn ticks(start: Float, stop: Float, count: Int) -> List(Float) {
  case count > 0, start == stop {
    False, _ -> []
    _, True -> [start]
    True, False -> {
      let reverse = stop <. start
      let spec = case reverse {
        True -> tick_spec(stop, start, count)
        False -> tick_spec(start, stop, count)
      }
      case spec {
        Error(Nil) -> []
        Ok(Spec(i1, i2, increment)) ->
          case i2 >= i1 {
            False -> []
            True -> emit(i1, i2, increment, reverse)
          }
      }
    }
  }
}

/// The increment between ticks, negative when it denotes a reciprocal.
///
/// `Error(Nil)` where d3 returns `NaN`: a degenerate range, a reversed range,
/// or a non-positive count.
pub fn tick_increment(
  start: Float,
  stop: Float,
  count: Int,
) -> Result(Float, Nil) {
  case tick_spec(start, stop, count) {
    Ok(Spec(_, _, increment)) -> Ok(increment)
    Error(Nil) -> Error(Nil)
  }
}

/// The signed step between ticks, always a real step rather than a reciprocal.
///
/// This is what a caller wants for formatting — `format.tick_format` takes a
/// step, not an increment.
pub fn tick_step(start: Float, stop: Float, count: Int) -> Result(Float, Nil) {
  let reverse = stop <. start
  let increment = case reverse {
    True -> tick_increment(stop, start, count)
    False -> tick_increment(start, stop, count)
  }
  use increment <- result_map(increment)
  let magnitude = case increment <. 0.0 {
    True -> 1.0 /. float.negate(increment)
    False -> increment
  }
  case reverse {
    True -> float.negate(magnitude)
    False -> magnitude
  }
}

/// Extend `start` and `stop` outward to values that fall on tick boundaries.
///
/// Iterates because widening the bounds can change the chosen step, which can
/// change the bounds again. It terminates when the step stops moving — d3's own
/// condition, and in practice one or two iterations.
///
/// ```gleam
/// nice(0.3, 9.1, 5)  // #(0.0, 10.0)
/// ```
pub fn nice(start: Float, stop: Float, count: Int) -> #(Float, Float) {
  nice_loop(start, stop, count, Error(Nil))
}

fn nice_loop(
  start: Float,
  stop: Float,
  count: Int,
  previous: Result(Float, Nil),
) -> #(Float, Float) {
  case tick_increment(start, stop, count) {
    // No finite step, or the step has stopped moving: this is as nice as it gets.
    Error(Nil) -> #(start, stop)
    Ok(step) ->
      case Ok(step) == previous || step == 0.0 {
        True -> #(start, stop)
        False -> {
          let #(lo, hi) = case step >. 0.0 {
            True -> #(
              float.floor(start /. step) *. step,
              float.ceiling(stop /. step) *. step,
            )
            False -> #(
              float.ceiling(start *. step) /. step,
              float.floor(stop *. step) /. step,
            )
          }
          nice_loop(
            shed_negative_zero(lo),
            shed_negative_zero(hi),
            count,
            Ok(step),
          )
        }
      }
  }
}

// --- internals ------------------------------------------------------------

/// Turn negative zero into zero.
///
/// `nice` reaches negative zero honestly: IEEE says `ceiling(-0.5)` is `-0.0`,
/// and the sign survives the multiplication back, so a domain that ought to end
/// at zero ends at `-0.0`. That value compares equal to `0.0` and prints
/// differently, which is the worst pairing available — it will not show up in a
/// test that checks the number and will show up in an axis label.
///
/// d3 has the same behaviour; the fixture generator normalises it on the way
/// out, so this keeps the port honest rather than diverging from it.
///
/// Adding zero is exact: IEEE gives `-0.0 +. 0.0 == 0.0` and leaves every other
/// value untouched, so this needs no branch.
fn shed_negative_zero(x: Float) -> Float {
  x +. 0.0
}

fn tick_spec(start: Float, stop: Float, count: Int) -> Result(Spec, Nil) {
  // d3 reaches these through `Math.log10(0)` and `Math.log10(negative)`, both
  // of which yield NaN and propagate. Gleam has no NaN, so they are rejected.
  case count > 0 && stop >. start {
    False -> Error(Nil)
    True -> Ok(spec_of(start, stop, count))
  }
}

fn spec_of(start: Float, stop: Float, count: Int) -> Spec {
  let step = { stop -. start } /. int.to_float(count)
  let power = format.exponent10(step)
  let error = step /. format.power_of_ten(power)
  let factor = case error >=. e10, error >=. e5, error >=. e2 {
    True, _, _ -> 10.0
    _, True, _ -> 5.0
    _, _, True -> 2.0
    _, _, _ -> 1.0
  }

  let spec = case power < 0 {
    True -> {
      // Reciprocal form: multiply by `inc` and divide to recover the value.
      let inc = format.power_of_ten(-power) /. factor
      let i1 = format.round_toward_positive(start *. inc)
      let i2 = format.round_toward_positive(stop *. inc)
      let i1 = case int.to_float(i1) /. inc <. start {
        True -> i1 + 1
        False -> i1
      }
      let i2 = case int.to_float(i2) /. inc >. stop {
        True -> i2 - 1
        False -> i2
      }
      Spec(i1, i2, float.negate(inc))
    }
    False -> {
      let inc = format.power_of_ten(power) *. factor
      let i1 = format.round_toward_positive(start /. inc)
      let i2 = format.round_toward_positive(stop /. inc)
      let i1 = case int.to_float(i1) *. inc <. start {
        True -> i1 + 1
        False -> i1
      }
      let i2 = case int.to_float(i2) *. inc >. stop {
        True -> i2 - 1
        False -> i2
      }
      Spec(i1, i2, inc)
    }
  }

  // A single requested tick can bracket to nothing. d3 retries at double the
  // count rather than returning an empty axis.
  case spec.i2 < spec.i1 && count == 1 {
    True -> spec_of(start, stop, 2)
    False -> spec
  }
}

/// Walks the index range in whichever direction lets each value be prepended,
/// so the list comes out in the required order without a reversal pass.
fn emit(i1: Int, i2: Int, increment: Float, reverse: Bool) -> List(Float) {
  case reverse {
    False -> down_from(i2, i1, increment, [])
    True -> up_from(i1, i2, increment, [])
  }
}

fn down_from(
  i: Int,
  limit: Int,
  increment: Float,
  acc: List(Float),
) -> List(Float) {
  case i < limit {
    True -> acc
    False -> down_from(i - 1, limit, increment, [value(i, increment), ..acc])
  }
}

fn up_from(
  i: Int,
  limit: Int,
  increment: Float,
  acc: List(Float),
) -> List(Float) {
  case i > limit {
    True -> acc
    False -> up_from(i + 1, limit, increment, [value(i, increment), ..acc])
  }
}

/// Dividing by the negated reciprocal rather than multiplying by a fraction is
/// the whole point of the negative increment: `0.1` is not representable in
/// binary and `10.0` is, so `3.0 /. 10.0` is exact where `3.0 *. 0.1` is not.
fn value(index: Int, increment: Float) -> Float {
  let x = int.to_float(index)
  case increment <. 0.0 {
    True -> x /. float.negate(increment)
    False -> x *. increment
  }
}

fn result_map(r: Result(a, e), f: fn(a) -> b) -> Result(b, e) {
  case r {
    Ok(v) -> Ok(f(v))
    Error(e) -> Error(e)
  }
}
